spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: rds
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    # OSIV 끔
    # 참고 URL : https://ykh6242.tistory.com/entry/JPA-OSIVOpen-Session-In-View%EC%99%80-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94
    open-in-view: false
  h2.console.enabled: false
  sql.init.mode: always

# mail properties
mail:
  smtp:
    auth: true
    starttls:
      enable: true
      required: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

# admin 구글 계정
AdminMail:
  id:  sdj799@gmail.com
  password:  = kkxo umty tisf yrzj
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver

