### 회원 가입
POST http://localhost:8080/api/v1/user/signUp
Content-Type: application/json

< ./request/signUp.json


### 아이디 중복 체크
POST http://localhost:8080/api/v1/user/userIdDuplicateCheck
Content-Type: application/json

< ./request/userIdDuplicateCheck.json


### 닉네임 중복 체크
POST http://localhost:8080/api/v1/user/nickNameDuplicateCheck
Content-Type: application/json

< ./request/nickNameDuplicateCheck.json


### 로그인
POST http://localhost:8080/api/v1/signIn
Content-Type: application/json

< ./request/signIn.json

### 이메일 인증 코드 발송
POST http://localhost:8080/api/v1/sendAuthenticationEmailCode
Content-Type: application/json

< ./request/sendAuthenticationEmailCode.json


### JWT 를 활용한 인증 테스트
GET http://localhost:8080/api/v1/user/test
ACCESS_TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5b3lrc2tzM0BnbWFpbC5jb20iLCJpYXQiOjE2OTQ1ODcwNzEsImV4cCI6MTY5NDU4NzEzMSwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJ0b2tlblR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJuaWNrbmFtZSI6IuylrOy5tDExIn0.eh3Y4vRJnmfLCkdT2KPsSX6xNrC3MWOJyLCH67kpf2tShdczmi0HdXZr-PlOfZDC9FRn8YvMYcK4ZtPWgVk8Jg
REFRESH_TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5b3lrc2tzM0BnbWFpbC5jb20iLCJpYXQiOjE2OTQ1ODcwNzEsImV4cCI6MTY5NDU4NzI1MSwianRpIjoiZWE1ZWM2MTgtNTE0Mi00Y2QyLWFkZmEtNGU3MTNlZWIxMzk4IiwidG9rZW5UeXBlIjoicmVmcmVzaF90b2tlbiIsIm5pY2tuYW1lIjoi7KWs7Lm0MTEifQ.vDfrB4uU0xP6hQwrnNNhHY-DrOfpASXvxvvuZ-SXFbs5rvIzb_vtSZ1xpXjSUJN629A1CUvdqo4bL4Jchpl8oQ

### 토큰 갱신 테스트
GET http://localhost:8080/api/v1/updateToken
ACCESS_TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5b3lrc2tzM0BnbWFpbC5jb20iLCJpYXQiOjE2OTQ1ODc5NTgsImV4cCI6MTY5NDU4ODAxOCwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJ0b2tlblR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJuaWNrbmFtZSI6IuylrOy5tDExIn0.KYPVN0gL7fK2hpSSDzVkL7mbFurt7WFxA3YiXuNGeRKlN5N5_J4xsZroIEQqN2Zrd7yUtHzaw6NQ_nlERXpobQ
REFRESH_TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5b3lrc2tzM0BnbWFpbC5jb20iLCJpYXQiOjE2OTQ1ODc5NTgsImV4cCI6MTY5NDU4ODEzOCwianRpIjoiZmUyY2Y2NzUtZDhlYS00NmY5LTgzMDctOWZmNzNiNzljMjY2IiwidG9rZW5UeXBlIjoicmVmcmVzaF90b2tlbiIsIm5pY2tuYW1lIjoi7KWs7Lm0MTEifQ.Gd4rqMXsz-McxwDPFfHvzCInDmy9Lc_InETiRr-Fk4LPyosbUqbQmi_GSmvjtEn8h-6W4wmeJ_HX365Nn1OsxA